CREATE DATABASE newsletter;

CREATE TABLE IF NOT EXISTS emails (
	id SERIAL PRIMARY KEY,
  	email VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS login (
	id SERIAL PRIMARY KEY,
  	email VARCHAR(80) NOT NULL UNIQUE,
  	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS newsletter_texts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(80) NOT NULL,
	text TEXT NOT NULL
)